### ISSUE TITLE
Openweathermap returns a 401 error code : Invalid API Key

### ISSUE THREAD

**Issue by vinpav** [kalliope-project/kalliope_neuron_openweathermap#3] opened 2018-07-25 09:29 UTC
Hi,

The current version of the openweathermap neuron does not work with a free openweathermap account.

The problem comes from the "forecast = owm.daily_forecast(extended_location)" line, as the 16 days/daily forecast API calls requires a paid subscription to openweathermap (take a look at [this chart](https://openweathermap.org/price) for more info).

Currently a free openweathermap subscription gives only access to : 

- Current weather data (urls starting with http://api.openweathermap.org/data/2.5/weather/)
- 5 day / 3 hour forecast (urls starting with http://api.openweathermap.org/data/2.5/forecast/)

It took me quite some time to figure this out, so I tought it was worth mentionning that.
(Thanks for the goob work on Kalliope !)

**Comment by Sispheor** [comment] 2018-07-25 09:36
It was working, so something changed on their side recently.
I'll take a look, thank you for the hint.

**Comment by Sispheor** [comment] 2018-07-25 09:46
Can you give a try by adding limit=5 to the line? So we are in free user limit ranges.

**Comment by vinpav** [comment] 2018-07-25 09:57
Same result with http://api.openweathermap.org/data/2.5/forecast/daily?q=paris&limit=5&appid=XXX
>> {"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}

It looks like http://api.openweathermap.org/data/2.5/forecast/daily is forbidden to free accounts.

**Comment by Sispheor** [comment] 2018-07-25 12:31
OK, I'll see with the lib owner if we have a workaround for this. 
I can see that we are not using the last version. Maybe is already handled in the last version.

**Comment by Sispheor** [comment] 2018-07-26 07:19
Seems an issue on the API. 
Do you have the same issue as [this one](https://github.com/csparpa/pyowm/issues/237)?

**Comment by vinpav** [comment] 2018-07-26 12:10
Yes, it's the same issue. But again, I don't think this must be considered like a bug because the API response with a free account fits the price chart on the openweathermap website.
16 days/daily forecast API = http://api.openweathermap.org/data/2.5/forecast/daily = owm.daily_forecast(...) = requires a paid subscription.
(But, I might be misunderstanding)
Anyway, I'd be happy if there's a way to make this work with a free account ;)

**Comment by Sispheor** [comment] 2018-07-26 13:01
ok. I don't see any workaround to get the "tomorrow" weather with the lib. 
I'm not sure this is handled so far.

**Comment by vinpav** [comment] 2018-07-26 13:37
According to what I've seen in the API, there is a solution to get some detailed forecast information for the next 5 days.

Using the "5 days/3 hour forecast API", available with a free account, you can get the 5 next days forcast by 3 hours periods. With good python skills (which I don't have), it might be possible to regroup all these data day by day and compute the results : day X pressure = average pressure for that day, day X min temperature = min temperature for that day, day X precipitations = sum of precipitations for that day, etc.
Though, it seems to represent a rather huge effort for a result that would probably not be fully satisfying.

For now I've just commented the "tommorow" part of the neuron to make the "today" weather work.
Thanks for the feedback on this issue !

**Comment by Sispheor** [comment] 2018-07-26 13:40
Yes, I know that it's possible to request on the api directly. The fact is taht we are using a lib to facilitate this step.
And the idea is to stick on this lib. My question was, is the lib aware of this potential change? Do we have another call that can do the trick?
I'll check this when I have time. 

Thanks for pointing out the issue.

**Comment by Sispheor** [comment] 2018-08-12 22:24
Current weather and forecast ok.
Neuron updated.

**Comment by vinpav** [comment] 2018-08-13 17:25
Same problem with V2 update of this neuron : 

> pyowm.exceptions.api_response_error.UnauthorizedError: Your API subscription level does not allow to perform this operation
> Reason: Invalid API Key provided

I'm still using a free API key. Am I missing something ?

**Comment by Sispheor** [comment] 2018-08-13 19:17
Show us your synapse. (Cut some letters of your key)

**Comment by vinpav** [comment] 2018-08-13 19:45
```
- name: "weather-summary"
  signals:
      - order: "quel temps fait il"
  neurons:
      - openweathermap:
          api_key: "25xxxxxxxxxxxxxxxxxxxxxxbaa"
          lang: "fr"
          temp_unit: "celsius"
          location : "paris"
          country: "FR"
          say_template:
              - "Actuellement à {{ location }} : {{ current['weather_status'] }} avec une température de {{ current['temp'] }} degrés."
```

**Comment by Sispheor** [comment] 2018-08-13 19:52
looks good.
weird, no typo in the api key? a space or something?

**Comment by daylicron** [comment] 2018-08-13 19:57
I can confirm the issue.
Exception in kalliope debug log on pastebin: https://pastebin.com/5T6iZevb

I'm using up to date pyown version 2.6.1 from pip:
``pip install pyowm
Requirement already satisfied: pyowm in /usr/local/lib/python3.6/dist-packages (2.6.1)``

My synapse:

```
   - name: "getthe-weather"
     signals:
       - order: "Wie wird das Wetter"
       - order: "Wie ist das Wetter"
       - order: "Wie ist das Wetter heute"
     neurons:
       - openweathermap:
           api_key: "e9ecxxxxxxxxxxxxxxxxxxxxxxxxe2d6"
           lang: "de"
           temp_unit: "celsius"
           location: "Berlin"
           country: "DE"
           say_template:
           - "Heute wird das Wetter {{ weather_today }} bei einer Temperatur von {{ temp_today_temp }} Grad."
```

**Comment by Sispheor** [comment] 2018-08-13 20:11
So weird, we don't have the issue with @corus. Maybe because we have an old API key.

**Comment by vinpav** [comment] 2018-08-13 20:26
@Sispheor this is what I've been thinking about. Anyway, this neuron does not work for "recent" openweathermap users. Maybe you can confirm that by generating a new key / creating a new account.
I'll switch to my previous "disappointing-current-weather-data-only" version for the moment.

**Comment by Sispheor** [comment] 2018-08-13 22:07
You are using pyowm version 2.6.1?
We've updated it to 2.9.0. Can you give a try?
`pip install --upgrade pyown`

**Comment by vinpav** [comment] 2018-08-14 07:26
I'm using pyown 2.9.0 and I have the issue.
Run your code with a recent free API key and you'll probably reproduce this issue.

**Comment by daylicron** [comment] 2018-08-14 17:34
> I'm using pyown 2.9.0 and I have the issue.

I can confirm this. Uptdating to pyowm 2.9.0 didnt't do the trick.

**Comment by Sispheor** [comment] 2018-08-15 08:25
Let's re open it then !

**Comment by corus87** [comment] 2018-08-15 12:20
I looked into it and I can confirm it seems related to our "old" keys. With a new key, I have the same problem. 

With the function three_hours_forecast() I'm able to get a forecast of 5 days for every 3 hours and also weather_at_place() is working which is for the current weather conditions.

So we have to rebuild the neuron again, to make sure everyone gets the weather. I will try to make a PR till the end of the weekend.

**Comment by Sispheor** [comment] 2018-08-15 12:22
Thanks a lot!

**Comment by Sispheor** [comment] 2018-08-19 08:13
I took a look to the update.
I just feel uncomfortable with the fact that it looks like a trick to keep having for free something that is now reserved to paid user. 
@LaMonF what do you think?

**Comment by daylicron** [comment] 2018-08-19 14:54
> I took a look to the update.
> I just feel uncomfortable with the fact that it looks like a trick to keep having for free something that is now reserved to paid user.
> @LaMonF what do you think?

What exactly to you mean? I checked the pricing for the OWM API and I think, things should be OK there. Take a look at the [pricing](https://openweathermap.org/price).  5 days forecast and current day weather should work.

**Comment by Sispheor** [comment] 2018-08-19 15:53
We need to define clearly what we want to return. As the 5 days forecast is only for a 3 hour range.
How do we propose this as neuron input? The user provide the range of hours he wants?
We provide a dict of range and then the user take the one he wants in his template? We calculate the average from all range we got?

**Comment by daylicron** [comment] 2018-08-19 16:21
First of all I think about a switch. The user can set in the brain, if he pays for OWM or not.As default I would say, people use the free version.  Using this switch we can say, that we provide the forecast the user asks for(paying users) or only the 5days/3hours forecast(free users).

Talking about what we provide for 5days/3hours forecast: How does OWM calculates  the dayli forecast? I don't know, someone who pays for OWM could find out, by comparing 5days/3 hours and dayli forecast. If they only use the max_temperature value for saying what temperature is gonna be, that should be an easy one.

But: I think it would be a nice feature to hand over the time period manually. I could imagine asking kalliope, what the weather will be in the morning. In my case this would mean: If it will be sunny/nice I'll set my alarm 30 minutes earlier to go by bicycle to work. If it will be rainy, I'll take the subway.

**Comment by Sispheor** [comment] 2018-08-23 15:53
New version [here ](https://github.com/kalliope-project/kalliope_neuron_openweathermap/tree/v2_for_new_api_key)ready for testing.

**Comment by Sispheor** [comment] 2018-08-23 18:35
Update pushed in master branch. We're good I think this time

**Closed as completed by Sispheor** 2018-08-23 18:35 UTC

**Comment by vinpav** [comment] 2018-08-24 07:07
Great ! I'll give it a try asap.

**Comment by vinpav** [comment] 2018-08-31 08:55
Hi ! Thanks for the update on the openweathermap neuron, I have installed and tested it yesterday and it works.
However I'd like to tell you about a few things, but I don't know if it should be considered as bugs or improvements. May we discuss it here or do I have to open a new issue ?

**Comment by Sispheor** [comment] 2018-08-31 09:55
Come on the gitter chat to discuss about it and then we can open an issue if needed.

**Comment by openweather-me** [comment] 2019-07-07 09:07
Hi. Just registered account and received welcome email. In the email I have link for test API key in browser. But error telling me that key not valid.
{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}

Also I tried to create new key in the web panel but same. Key is invalid.

Thank you.

**Comment by openweather-me** [comment] 2019-07-07 09:11
Solved...
Guys you are little bit tricky!
Why you cannot send to welcome account as normal VISIBLE text your hidden link?
My mail client is blocking remote content! I think not only my.

Thank you for your work. :)
